version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8500:8500"
    volumes:
      - ./app:/app
    command: 
      sh -c "python manage.py runserver 0.0.0.0:8500"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=Passw0rd
    depends_on:
      - db

  db:
    image: postgres:16rc1-alpine3.18
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=Passw0rd

volumes:
  dev-db-data:
